### ISSUE TITLE
Syntax error for installing Scoop in 3rd script

### ISSUE THREAD

**Issue by windowz414** [ucoruh/cpp-cmake-ctest-template#1]
I'll just post the error here, no need to elaborate further.

I can't be bothered to fix it as I tried many workarounds but to no avail. Although one thing, I'd recommend that you rewrite that script in PowerShell instead of CMD script, doing so should resolve most of the errors.

```
At line:1 char:5
+ iex & {$(irm get.scoop.sh)} -RunAsAdmin
+     ~
The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double
quotation marks ("&") to pass it as part of a string.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : AmpersandNotAllowed
```

**Comment by ucoruh** [comment]
Can you try latest optimized version, It doesn't give error. https://github.com/ucoruh/cpp-cmake-ctest-template/blob/main/3-install-package-manager.bat
