### ISSUE TITLE
Missing solution file

### ISSUE THREAD

**Issue by windowz414** [ucoruh/cpp-cmake-ctest-template#3]
I wanted to import this project to Visual Studio, but how am I supposed to do that if the solution file is missing? Are we supposed to use Visual Studio Code instead?

**Comment by ucoruh** [comment]
I'll explain it also in the classroom. This project utilizes the CMake build system and offers two methods for development using Visual Studio Community Edition:

Direct Folder Opening: You can open the project folder directly in Visual Studio Community Edition, which has native support for CMake projects. This approach allows you to work directly on the project without needing to generate a Visual Studio solution file. Additionally, this method supports both Windows Subsystem for Linux (WSL) and remote connections to WSL.

Generate Visual Studio Solution File: Alternatively, you can run the batch script located at [this GitHub repository](https://github.com/ucoruh/cpp-cmake-ctest-template/blob/main/9-clean-configure-app-windows.bat) to generate a Visual Studio solution file. Working this way does have a limitation: if you add new files to the project, you will need to place them in the src/ folder and then regenerate the solution file for the changes to take effect.

Choose the method that best suits your workflow.
